name: Tests
on: [push]
  # schedule:
  #   - cron: '00 17 * * 5'

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Get the disk space free
      run: df -h .

    - name: Setup and test
      run: |
        ./test.sh